---
functional:
  - Пользователь должен иметь возможность регистрироваться и входить в систему с использованием собственных
    учетных записей, или с использованием сторонних ресурсов (OAuth)
  - Пользователь должен иметь возможность попробовать "Простой бой". Регистрация не требуется
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность настройки конфигурации игры (Уровень, тип, время, название)
  - Пользователь должен иметь возможность присоединиться к уже созданной игре
  - Пользователь должен иметь возможность отправлять сообщения в чат
  - Пользователь должен иметь возможность выбирать язык программирования для решения задачи
  - Пользователь должен иметь возможность сбросить решение в редакторе
  - Пользователь должен иметь возможность наблюдать за игрой в качестве зрителя
  - Пользователь должен иметь возможность завершить игру
  - Пользователь должен иметь возможность принимать участие в турнирах
  - Пользователь должен иметь возможность просматривать главное лобби игр
  - Пользователь должен иметь возможность просматривать историю поединков с возможностью воспроизведения
  - Пользователь должен иметь возможность просматривать завершенные игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен предоставлять возможность пользователям видеть статус онлайн-присутствия других игроков
  - Сайт должен обеспечивать возможность пользователю и его сопернику видеть один экран одновременно при решении задач
  - Сайт должен предоставлять возможность просматривать рейтинг игроков с удобством и актуальностью
  - Сайт не должен выдавать ошибок в консоли браузера при его использовании