---
functional:
  - Пользователь должен иметь возможность создать учетную запись на сайте
  - Пользователь должен иметь возможность войти в систему с использованием своих учетных данных
  - Пользователь должен иметь возможность войти в систему с использованием сторонних ресурсов (OAuth)
  - Пользователь должен иметь возможность попробовать "Простой бой". Регистрация не требуется
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность настройки конфигурации игры (Уровень, тип, время, название)
  - Пользователь должен иметь возможность присоединиться к уже созданной игре
  - Пользователь должен иметь возможность отправлять сообщения в чат
  - Пользователь должен иметь возможность отправлять личные сообщения другим игрокам
  - Пользователь должен иметь возможность выбирать язык программирования для решения задачи
  - Пользователь должен иметь возможность сбросить решение в редакторе
  - Пользователь должен иметь возможность наблюдать за игрой в качестве зрителя
  - Пользователь должен иметь возможность завершить игру (Сдаться или проверить решение)
  - Пользователь должен иметь возможность создавать/завершать/принимать участие в турнирах
  - Пользователь должен иметь возможность просматривать историю поединков и воспроизводить их
  - Пользователь должен иметь возможность менять язык в описании задачи
  - Пользователь должен иметь возможность быстрого просмотра информации о другом пользователе
  - Пользователь должен иметь возможность переключаться между страницами таблицы рейтинга игроков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть адаптивным и хорошо отображаться на разных устройствах
  - Сайт должен соответствовать всем применимым законам и нормативным актам, включая, закон об авторских правах, 
    защите данных, антимонопольным нормам, антидискриминационным законам, кибербезопасности, анти-спамом и охране детей
implicit:
  - Сайт должен предоставлять возможность пользователям видеть статус онлайн-присутствия других игроков
  - Сайт должен обеспечивать возможность пользователю и его сопернику видеть один экран одновременно при решении задач
  - Сайт не должен выдавать ошибок в консоли браузера при его использовании
  - Сайт должен предоставлять уведомления пользователям, такие как приглашения к игре, 
    сообщения и уведомления о событиях в игре
  - Сайт должен поддерживать постоянную сессию пользователей путем использования соответствующих cookies для 
    хранения сведений о сеансе и авторизации
  - Сайт должен поддерживать несколько языков интерфейса (Русский, Английский)
  - Сайт должен проверять подлинность учетных данных пользователя и разрешать вход только при верных данных
  - Пользователь должен иметь возможность просматривать рейтинг игроков с помощью фильтров и сортировки, 
    а информация о рейтинге должна обновляться не реже одного раза в день